#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Keep this URL in sync with the font families/weights used in `src/styles/global.css`.
GOOGLE_FONTS_CSS_URL="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&family=Noto+Serif+Display:wght@400;700&display=swap"

OUT_FONTS_DIR="$ROOT_DIR/public/fonts"
OUT_CSS_FILE="$ROOT_DIR/src/styles/fonts.css"

mkdir -p "$OUT_FONTS_DIR"

tmp_css="$(mktemp)"
tmp_css_out="$(mktemp)"

cleanup() {
  rm -f "$tmp_css" "$tmp_css_out"
}
trap cleanup EXIT

echo "Fetching Google Fonts CSS..."

# Use a modern UA so Google returns WOFF2 sources.
curl -fsSL \
  -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
  "$GOOGLE_FONTS_CSS_URL" > "$tmp_css"

mapfile -t urls < <(grep -oE 'https://fonts\.gstatic\.com[^)]*\.woff2' "$tmp_css" | sort -u)

if [[ "${#urls[@]}" -eq 0 ]]; then
  echo "ERROR: No .woff2 URLs found in the CSS. Google may have changed the response format."
  exit 1
fi

echo "Downloading ${#urls[@]} font file(s) into $OUT_FONTS_DIR ..."

for u in "${urls[@]}"; do
  # Fonts URLs usually do not include query params, but strip them just in case.
  clean="${u%%\?*}"
  file="$(basename "$clean")"

  # Avoid re-downloading if file already exists.
  if [[ -f "$OUT_FONTS_DIR/$file" ]]; then
    continue
  fi

  curl -fsSL "$clean" -o "$OUT_FONTS_DIR/$file"
done

# Rewrite URLs in the CSS so fonts are loaded from your own domain.
sed -E \
  's@https://fonts\.gstatic\.com[^)]*/([^/?]+\.woff2)@/fonts/\1@g' \
  "$tmp_css" > "$tmp_css_out"

cat > "$OUT_CSS_FILE" <<'HEADER'
/*
Self-hosted fonts (generated).

This file was generated by `./scripts/selfhost-fonts.sh`.
Do not hand-edit unless you know what you're doing.
*/

HEADER

cat "$tmp_css_out" >> "$OUT_CSS_FILE"

echo "Wrote $OUT_CSS_FILE"
echo "Done."
